import Link from 'next/link';
import { getConfig, publicConfigSummary } from '@/lib/config/env.ts';

export const dynamic = 'force-dynamic';

export default function SettingsPage() {
  const config = publicConfigSummary(getConfig());
  return <main className="shell"><header className="topbar"><Link className="brand" href="/"><span className="brand-mark">C</span><span>CATALYST <small>RESEARCH DESK</small></span></Link><nav><Link href="/">Workspace</Link><Link href="/reports">Reports</Link><a className="active" href="/settings">Settings</a></nav><span className="research-only">RESEARCH ONLY</span></header><section className="content"><p className="eyebrow">APPLICATION</p><h1>Settings & data sources</h1><p className="muted">Safe configuration summary. Secret values are never displayed.</p><section className="panel"><h3>AI research</h3><div className="indicator-row"><span>Qwen connection</span><strong>{config.ai.configured ? 'Configured' : 'Not configured'}</strong></div><div className="indicator-row"><span>Model</span><strong>{config.ai.model}</strong></div><div className="indicator-row"><span>Strict validation</span><strong>{config.ai.strictValidation ? 'On' : 'Off'}</strong></div><h3>Market data</h3><div className="indicator-row"><span>Mode</span><strong>{config.demoMode ? 'Demo only' : 'Provider fallback'}</strong></div><div className="indicator-row"><span>Provider order</span><strong>{config.providers.order.join(' → ')}</strong></div>{Object.entries(config.providers.keys).map(([provider, state]) => <div className="indicator-row" key={provider}><span>{provider} API key</span><strong>{state}</strong></div>)}<h3>Freshness</h3><div className="indicator-row"><span>Quote cache</span><strong>{config.cache.ttlQuoteSeconds}s</strong></div><div className="indicator-row"><span>Stale after</span><strong>{config.cache.staleAfterSeconds}s</strong></div></section>{config.warnings.length > 0 && <section className="panel"><h3>Configuration notes</h3>{config.warnings.map((warning) => <p className="warning" key={warning}>{warning}</p>)}</section>}</section></main>;
}
